notifications:
  email: false

language: perl
perl:
# Params::Classify breaks in 5.26, and Lingua::EN::Tagger needs upgrading
  - "5.26" # bionic

cache:
  directories:
    - ~/.npm
    - node_modules

env:
  global:
    - "S3_BUCKET=fixmystreet-bundle-cache"
    - "CYPRESS=0"
    - secure: "llgWNfR/8pH0HjYpg+xhVxuqTaLC0GGUugfuINiUap7JxzjCZ2rlryxCXA4BCM8GUHa9wlYKhrKCSx+DM3EHRE0cLei7LNxAK1JSXLj3NihFQhqnq64tjDwGCSA4l7mlqErA7DK4Dpmh+hBp5f680akITAInM92CbwQZxLDYaCU="
    - secure: "qW+WCgAF68itADxcbcq+nCnKx3vf3GX73HMfjfbkFFUsYmIR+ZaJ9yQMnGJwxIpCHTWLAeqyx4KO8N8T3GmNdKYzIMZemOzp4ED29YC31QOQeq1CwNp2hD5sq/o47d2BzXWwMYNvNXfxz1K6r2c6EMPUtu8X3B8ExZq1RzSFdXs="

sudo: false

addons:
    apt:
        packages:
            - gettext
            - language-pack-de
            - language-pack-nb

install:
  - .travis/install
before_script:
  - commonlib/bin/gettext-makemo FixMyStreet
script:
  - 'script/test --jobs 3 t'
after_success:
  - .travis/after_script
