permalink: pretty
exclude: [ vendor ]
paginate: 10
gems:
  - jekyll-paginate
paginate_path: "/blog/:num/"

authors:
  struan:
    display_name: Struan
  matthew:
    display_name: Matthew
  zarino:
    display_name: Zarino

# https://github.com/RobertDeRose/jekyll-livereload/
# Enable livereload by default when running `jekyll serve` locally.
# (Doesn't do anything on Github Pages.)
livereload: true
