permalink: pretty
exclude: [ vendor ]
paginate: 10
gems:
  - jekyll-paginate
paginate_path: "/blog/:num/"

authors:
  struan:
    display_name: Struan
  matthew:
    display_name: Matthew
  zarino:
    display_name: Zarino
