safe: true
highlighter: pygments
baseurl: /
permalink: pretty
markdown: kramdown
exclude: [ node_modules, bower_components ]

authors:
  struan:
    display_name: Struan
  matthew:
    display_name: Matthew
